import { createContext } from "react";

const contextData = createContext({
    "home" : "Home",
    "bolly": "Bollywood",
    "techno": "Technology",
    "holly": "Hollywood",
    "fit" : "Fitness",
    "foo" : "Food",
    "the" : "The",
    "siren" : "Siren",
    "firstTitle" : "Title of vertical Gallery",
    "secTitle" : "The Sound cloud",
    "secTitleBr" : "You loved is doomed",
    "travDate":"Travel / Augest 21 2017",
    "travel"  : "Travel",
    "travelDate" : "/ Augest 21 2017",
    "latest" : "The Latest",
    "imgCardTitle" : "Joshua Tree",
    "imgCardTitleBr" : "Overnight Adventure",
    "imgCardInfo" : "Gujarat is vastly underrated and it’s a mystery to us why the region isn’t more well-known as a tourist destination. It has a plethora of temples and palaces",
    "articles" : "Latest Articles",
    "waveHeading" : "Catch waves with", 
    "waveHeadingBr" : "an adventure guide",
    "waveTextInfo": "Gujarat is vastly underrated and it’s a", 
    "waveTextInfoBr":"mystery to us why the region isn’t more well-",
    "galleryHead" : "Stylish Star Allu Arjun",
    "adverb" : "Advertistement",
    "post" : "Top Post",
    "topTitle": "Catch waves with", 
    "topTitleBr":"adventure guide",
    "proud":"Be Proud But Never Satisfied",
    "one": "1",
    "two":"2",
    "three":"3",
    "four":"4",
    "more": "VIEW MORE",
    "cardTech" : "TECH",
    "today" : "/ TODAY AT 11:54",
    "style" : "STYLE",
    "aug" : "/ AUGUST 21 2017",
    "btnName": "Get Started",
    "followers": "9.3k",
    "shareArt": "Share this article",
    "fivhead":"5 Ways to animate a React app.",
    "userName":"Dmitry Nozhenko",
    "userRead":"jan 28, 2019 10 min read",
    "contImgText":"Animation in ReactJs app is a popular topic and there are many ways to create different types of animations.Many developers create animation exclusively using css and adding classes to HTML tags. This is a great way and you should use it. If you want to create complex animations you can pay attention to GreenSock. GreenSock is the most powerful animation platform. There are also a lot of libraries, components for creating animation in React.",
    "talk":"Let’s talk about them",
    "react":"React",
    "js":"JavaScript",
    "ani":"Animation",
    "authInfo":"WRITTEN BY",
    "authName":"Dmitry Nozhenko",
    "authDat":"Jan 28, 2019 · 10 min read",
    "mSiren":"More From The Siren",
    "tagged":"Also tagged Reactjs",
    "tree":"Joshua Tree Overnight Adventure",
    "augdate":"Aug 10 · 4 min read",
    "authText":"Performance Comparison for 5 JavaScript Object Iterations",
    "clap":"Clap"
});

export {contextData}